sudo: required
services:
    - docker

before_install:
    - docker build -t aqrulesms/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true aqrulesms/react-test npm test

after_success:
    - docker build -t aqrulesms/multi-client ./client
    - docker build -t aqrulesms/multi-nginx ./nginx
    - docker build -t aqrulesms/multi-server ./server
    - docker build -t aqrulesms/multi-worker ./worker
    # log in to docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # take those images and push them to docker hub
    - docker push aqrulesms/multi-client
    - docker push aqrulesms/multi-nginx
    - docker push aqrulesms/multi-server
    - docker push aqrulesms/multi-worker

deploy:
    provider: elasticbeanstalk
    region: us-east-2
    app: multi-docker
    env: Multidocker-env
    bucket_name: elasticbeanstalk-us-east-2-168116352293
    bucket_path: docker-multi
    on:
        branch: main
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
